spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tigers?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=JST
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver